require 'asciidoctor/extensions'

include ::Asciidoctor

# Strip bogus tags generated by Asciidoctor
Extensions.register do
  postprocessor do
    process do |document, output|
      output = output.gsub(/<\/p>/, '')
      output
    end
  end
end
